# .streamlit/pages.toml

[[pages]]
path = "main.py"
name = "í™ˆ"
icon = "ğŸ "

[[pages]]
path = "pages/car_info.py"
name = "ìë™ì°¨ ì •ë³´"
icon = "ğŸš—"

[[pages]]
path = "pages/faq_pages.py"
name = "FAQ"
icon = "â“"
